name: 'Ejecutar Docker'
on: push
jobs:
  saludar:
    runs-on: ubuntu-latest
    name: 'Tarea para saludarme'
    steps: 
      - name: 'Ejecutar la accion del docker'
        id: hola
        uses: ina--docker-mg-nelson/accion@v1
        with:
          quien: 'Lucho'
      - name: 'Mostrar la hora obtenida'
        run: echo "La hora obtenida fue ${{ steps. hola.outputs.hora }}"
        
        
